// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0pz_ZMC5XaSSpxdloW2se3zQ6tx0NKZ4',
    appId: '1:33905260853:web:ed15e6cba7c615f919f47c',
    messagingSenderId: '33905260853',
    projectId: 'fruit-hub-f2837',
    authDomain: 'fruit-hub-f2837.firebaseapp.com',
    storageBucket: 'fruit-hub-f2837.firebasestorage.app',
    measurementId: 'G-3V0WRDT99P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS_qFDtW0DXi9tE60s9v3Osyelhp8O3Zc',
    appId: '1:33905260853:android:bc3922b73f9de57319f47c',
    messagingSenderId: '33905260853',
    projectId: 'fruit-hub-f2837',
    storageBucket: 'fruit-hub-f2837.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvRIv8G-1RjwASoQxRhXEzC-zZV6_3AXY',
    appId: '1:33905260853:ios:c3ef99c9823900dc19f47c',
    messagingSenderId: '33905260853',
    projectId: 'fruit-hub-f2837',
    storageBucket: 'fruit-hub-f2837.firebasestorage.app',
    iosBundleId: 'com.example.advancedEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvRIv8G-1RjwASoQxRhXEzC-zZV6_3AXY',
    appId: '1:33905260853:ios:c3ef99c9823900dc19f47c',
    messagingSenderId: '33905260853',
    projectId: 'fruit-hub-f2837',
    storageBucket: 'fruit-hub-f2837.firebasestorage.app',
    iosBundleId: 'com.example.advancedEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0pz_ZMC5XaSSpxdloW2se3zQ6tx0NKZ4',
    appId: '1:33905260853:web:1b7d177ba99b7e9519f47c',
    messagingSenderId: '33905260853',
    projectId: 'fruit-hub-f2837',
    authDomain: 'fruit-hub-f2837.firebaseapp.com',
    storageBucket: 'fruit-hub-f2837.firebasestorage.app',
    measurementId: 'G-LC5HGGK4DZ',
  );
}
